version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    network_mode: host
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
